os: linux
language: java
services:
  - docker
cache: bundler
dist: bionic

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: "Run failing tests"
      script: true

    - stage: deploy
      name: "Deploy to production"
      script: echo "Deploying..."

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT    




  


