os: linux

vm:
  size: large

language: java

services:
  - docker

jobs:
  include:
    - jdk: openjdk8
      name: "Test on OpenJDK 8"
      script:
        - echo "Testing on OpenJDK 8"
        - true  

    - jdk: openjdk11
      name: "Test on OpenJDK 11"
      script:
        - echo "Testing on OpenJDK 11"
        - true  

cache:
  directories:
    - $HOME/.m2  

dist: bionic

install: skip

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
