os: linux

vm:
  size: [large]
language: java
services:
  - postgresql
cache: bundler
dist: xenial
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
jobs:
  include:
    - name: failing
      script: true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
