
os: linux
vm:
  size: [large]
language: java
services:
  - docker
cache: bundler
dist: bionic

install: skip

jobs:
  include:
  rvm:
   - 2.5
   - 2.2
  env:
  - ISOLATED=true
  - ISOLATED=false
after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT


