os: linux
vm:
  size: large
language: python
services:
  - docker
cache:
  pip: true
dist: bionic

install:
  - pip install -r requirements.txt
  - pip list

jobs:
  include:
    - name: "Run Tests"
      os: linux
      dist: focal
      script:
        - python3 --version

    - name: "Generate SBOM"
      os: linux
      dist: focal
      addons:
        sbom:
          on:
            branch: 'main'
          run_phase: 'after_success'
          output_format: 'cyclonedx-json'
          input_dir: '.'
          output_dir: '/sbom/python'
      script:
        - echo "Generating SBOM"
        - mkdir -p /sbom/python # Ensure the output directory exists

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
  - ls /sbom/python

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
  - ls /sbom/python
