os: linux

vm:
  size: large

language: java
services:
  - docker

cache:
  directories:
    - $HOME/.m2  # Appropriate cache for Java instead of bundler

dist: bionic

install: skip

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: "Run Tests"
      script:
        - echo "Running tests..."
        - true  # Placeholder for actual test commands

    - stage: deploy
      name: "Deploy Application"
      if: branch = main AND type = push  # Ensures deployment runs only on push to main branch
      script:
        - echo "Deploying application..."
        - true  # Placeholder for deployment commands

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
