os: linux

vm:
  size: [large]
language: java
services:
  - docker
cache: bundler
dist: xenial  # Updated from bionic to xenial

install: skip

addons:
  snaps:
    - hugo  # Added Snap package

jobs:
  include:
    - name: failing
      script: true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT

