os: linux

vm:
  size: [large]
language: java
services:
  - docker
cache: bundler
dist: bionic

before_install:
  - git clone --depth=50 --branch=main https://$GITHUB_TOKEN@github.com/ViktorijaKrivokapic/TravisJava.git ViktorijaKrivokapic/TravisJava

install: skip

jobs:
  include:
    - name: failing
      script: true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo done
  - echo $TRAVIS_TEST_RESULT 

    
  

 







  


