os: linux
vm:
  size: large
language: python
services:
  - docker
cache:
  pip: true
dist: bionic

install:
  - pip install -r requirements.txt
  - pip list

jobs:
  include:
    - name: "Generate SBOM"
      os: linux
      dist: focal
      addons:
        sbom:
          on:
            branch: 'main'
          run_phase: 'script'
          output_format: 'cyclonedx-json'
          input_dir: '.'
          output_dir: '/sbom/python'
      script:
        - echo "Generating SBOM"
        - sudo mkdir -p /sbom/python # Ensure the output directory exists
        - ls -la # List the contents of the current directory for debugging
        - echo "Contents of the current directory"
        - ls -la /sbom # List the contents of the /sbom directory for debugging
        - echo "Contents of the /sbom directory"

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
  - ls -la /sbom/python # List the contents of the /sbom/python directory

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
  - ls -la /sbom/python # List the contents of the /sbom/python directory

