dist: focal
language: ruby
rvm:
  - 3.1
  - 3.2
  - 3.3

cache:
  - bundler

script:
  - bundle exec rspec

jobs:
  include:
    - &job
      stage: test runtime dependency installation
      if: commit_message !~ /skip:test_dependencies/ AND env(SKIP_TEST_DEPENDENCIES) IS blank
      cache: false
      install:
        - rvm use 3.3 --install --binary --fuzzy
        - gem build dpl.gemspec
        - gem install dpl-*.gem
        - nvm install 12.22.0
        - nvm use 12.22.0
        - gem update --system
        - nvm install 18.20.2
        - nvm use 18.20.2
        - node --version
      script:
        - .travis/test_install
    - <<: *job
      language: python
      python: 2.7


