
os: linux
vm:
  size: [large]
language: ruby
services:
  - docker
cache: bundler
dist: bionic
aws:
  authentication:
    token: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

install: skip

jobs:
  include:
    - rvm: 2.5
      env: ISOLATED=true
    - rvm: 2.2
      env: ISOLATED=false
after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT


