os: linux
dist: focal
language: ruby

# Specify Ruby version
rvm:
  - 2.7.8

script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo $TRAVIS_EVENT_TYPE
  - echo $(travis_internal_ruby)
  - ruby -v  # Print the Ruby version to confirm it is 2.7.8

deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN  
  keep_history: true
  on:
    branch: main
  # dpl_version: 1.x  # Ensure dpl 1.x is used as the default
  
  



