os: linux
dist: focal  # Changed from bionic to focal for compatibility with the SBOM addon
language: python  # Changed from java to python
services:
  - docker
cache: bundler
jobs:
  include:
    - name: "SBOM generation example job"
      addons:
        sbom: true  # Added to enable SBOM generation
      before_install:
        - pip install -r requirements.txt  # Install Python dependencies if needed
      script:
        - python generate_sbom.py  # Replace this with the command to generate your SBOM
after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT




