os: linux
dist: focal
language: node_js

jobs:
  include:
    - name: "test" # existing functionality
      script: # existing functionality
        - npm -v

    - name: "sbom" # SBOM generation job
      script: 
        - cd node
        - npm install
      addons:
        sbom:
          on:
            branch: 'main'
            pr: true
          condition: true
          run_phase: "after_failure" # Run SBOM generation after a failure
          output_format: "spdx-json" # Specify the SBOM output format
          output_dir: "/test" # Specify the output directory for SBOM
          input_dir: "/node" # Specify the input directory for SBOM

after_failure:
  - echo "SBOM generation failed"

after_success:
  - echo "SBOM generation succeeded"



 







  


