os: linux
vm:
  size: [large]
language: java
services:
  - docker
cache: bundler
dist: bionic

install: skip

jobs:
  include:
    - name: "SBOM generation example job"
      os: linux
      dist: focal
      addons:
        sbom: true  # Corrected syntax to enable SBOM addon
      # You can add other existing addons here if needed

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT







