os: linux
dist: bionic

language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - name: failing
      script: true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT





  


