
os: linux
vm:
  size: [large]
language: java
services:
  - docker
cache: bundler
dist: bionic
aws:
  authentication:
    token: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

install: skip
after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT


