os: linux

vm:
  size: large

language: java
services:
  - docker

# Correct caching for a Java project using Maven
cache:
  directories:
    - $HOME/.m2

dist: bionic

install: skip

jobs:
  include:
    - name: failing
      script: true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT

