os: linux

vm:
  size: [large]
language: java
services:
  - docker
cache: bundler
dist: bionic


install: skip

jobs:                             
  include:                        
    - os: linux
      dist: focal
      name: "SBOM generation example job"
      addons:
         sbom                    # new node
         <other existing addons>

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULTos: linux


