os: linux
vm:
  size: large
language: java
services:
  - docker
cache: bundler
dist: bionic

install: 
  - pip install -r requirements.txt
  - pip list

jobs:
  include:
    - os: linux
      dist: focal
      addons:
        sbom:
          on:
            branch: 'main'
          run_phase: 'after_success'
          output_format: 'cyclonedx-json'
          input_dir: '.'
          output_dir: '/sbom/python'
      script: true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT



 







  


