os: linux
dist: focal
language: node_js
node_js:
  - "14"  # Use a recent version of Node.js

jobs:
  include:
    - name: "test" # existing functionality
      script:
        - npm -v
    - name: "sbom" # SBOM generation job
      script:
        - cd node
        - npm install
      addons:
        sbom:
          on:
            branch: 'main'
            pr: true
          condition: true
          run_phase: "after_failure" # Run SBOM generation after a failure
          output_format: "spdx-json" # Specify the SBOM output format
          output_dir: "/test" # Specify the output directory for SBOM
          input_dir: "/node" # Specify the input directory for SBOM


