os: linux
dist: jammy
group: dev
language: shell

# Specify Ruby version
rvm:
  - 2.7.8

script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo $TRAVIS_EVENT_TYPE
  - ruby -v  

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
  dpl_version: 1.x  

