os: linux

vm:
  size: [large]
language: java
services:
  - docker
cache: bundler
dist: xenial
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true

jobs:
  include:
    - name: failing
      script: true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
