os: linux
dist: bionic
language: java
services:
  - docker  # Adding Docker service
cache: bundler

install: skip

jobs:
  include:
    - name: failing
      script: true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULTos: linux





