os: linux

vm:
  size: [large]
language: java
services:
  - docker
cache: bundler
dist: bionic
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres


install: skip

jobs:
  include:
    - name: failing
      script: true


after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT

