os: linux
dist: jammy
group: dev
language: shell

# Specify Ruby version
rvm:
  - 2.7.8

script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo $TRAVIS_EVENT_TYPE
  - ruby -v

deploy:
  provider: pages
  cleanup: false  # Replace skip_cleanup with cleanup and set it to false
  token: $GITHUB_TOKEN  # Use token instead of github_token
  keep_history: true
  on:
    branch: main
  dpl_version: 1.x


