os: linux

vm:
  size: large

language: java

services:
  - postgresql

cache:
  directories:
    - bundler

dist: bionic

install: skip

before_script:
  - psql -c 'create database test_db;' -U postgres

jobs:
  include:
    - name: failing
      script:
        - true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
