os: linux

vm:
  size: [large]
language: java
services:
  - docker
cache: bundler
dist: bionic
deploy:
  provider: pages:git
  token: <ZsyoexGcCTGqXoBry7hbilG1Kvlfim0U8mH6x30y3FkyDWyp4BwHXiQErJdFuwSKaaWcwjTUXBMSnd55NTPuVm9f370+gTdejykmB5oyrX7TjqRpVI+VtORqmG5sFXRsH5uuazpoTgWhvz3rjiCqsUjpzEpLgjsG22/eEKQaRn8vUm7W2lBwLHVpbqKE7SLDbG2ITa5yg//pmKCO/DEspL6b3M94GRHRpeZjWBjwaEAdHkhoZzOaMNZczNaJ6yBf9PK6c8KZs9CplUbVAKD9+7IxMuuvMR1vS1FAsRVhAebqedVisBa4Ooa66NCzczlIPkcQl0KxleKBY/xrG7E4EDUS+71x77jgoJRJ1s8YkR38gGmmnxwFF2A71E+f+oleEHJO/U1Yummpei5ATeZgml+BdSEIdzzQH5XUGFTQah3khc3YQTTuTalDsy3JFKZrKe6OkLwadVJvw5sT95gR2Uu/6diqf7afFzaFaGlNTp1rT7V7HloyKbqGUj0/kHst16hQp1aEs9qLsjSiv2RMChr0LuxA8c0TKJ91TVdOI5ylcVRtlOpAX/sED6Bt5WMzZZIOD40x8hsv4uPw2iHMQLZ0aPZQJp2krOWQJC3UdjYa4NYju6fmmr2rUB/yeUAeJYYDw+ZX3Fhz4w5JdxduhTdH7B3bc4Xh91gVBQhIZtE=>
  edge: true # opt in to dpl v2

install: skip

jobs:
  include:
    - name: failing
      script: true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT

ssh-key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCctycsJTQ3gkphS5CGRBXGzKG/M7RdHWBdYgTY/AyH84CQX6W6oU92sVJ/watzs7Nb7vqeugiKtPkJRrYV/bftiXCX+ovMm62LPdf89w919ptGQJYjDwe+jrc/Kf319rv/sVus2a6taGPDuPrkX+91gYDPk3WffhDeQGNs98yIkZDpMOaJn3iBS3CIQJXG7HG7geltwA0TsIHkXvWY/wzmS84dgEFkhJFq10zzReb/BpK8lnNqW6/CdoD+E8O1iWJZR2PPE1SOth43vyvreIkTUv6RBa9JvZyKNX7I+KGORFZicI2bRvfV+hG0X/3Vo/7Ew0zKu0wUElWcLqK9kMErhdJXr4mfre7SUDT1HPm3xye2y5CZWZ2GdoBfrH4T3x8ks0RLo74cdj8sk4wKxg87Y0yMNjzpcSoVzWqFOWF91sUBReTyyvWLl6ZkqrbTUYmfQdQyvJFswkOWgYGzxiS/Us7Sg6LKPAIOQ78BxP1Q7DqguPXVI5f13IePOr0bI6E= win 10@DESKTOP-962EV46
env:
  global:
    secure: AdgGBinhLkms9QrOMznm0h1XqI/gndcfZBuuD1bUvItuewlkYBVCWsH3zB5ciUe24jrNBCl/rh6goV4qOCRIXTT+SCJIyyEJQ1cT53MLtqmwTZ5WkPOf0GjujAtJ4RUwBQB6pHpKHo2QO1t+hiR7/+uNM1hS0cXKrbpzH45MLskwdoMQKk6/2lEcEuiul9hPhw4Ca5buEq7rhGjJsUlnnMBddfEXsQ1P3485NdWgIrxrZRuEW4oN883z4iFgvTaw8LpJqNtby8Gddn0xtmeMsAOcum9dXuIKBqmTbKxBfwt9QGCUfYFEdC92DsBCwmdzwYDmDJrIG/v6f+rhlNH36ni1SC7tL5cVumEJpz3E0+TDZv19yx0uWY/++hOc7/Yn9/+Nb9frNeNr0Lj8Fvi0E0eVbUFGximWjcL8OB5lubo65piWFc3J/0qjGX7vdxy54SMp1LiNWw0EqvwuHJ2g0BdCIAQLWWvAHkggILNHjPVpA7jdtHzMMJFLzTqXx83KfPUvb7pMKii6F+F4c8F2e5jp99kYhGqIgYoOtA/aSOJSxGmQskzb2Cq/wbGSCGYY5nHr09qpnMgiBy/4aGM3ZS0id6FZFn3iNJUxHnYw4sMxfW8skH9PYlFvSW7aTsXcrl6+bpXbUko1xvfpgoboBCPsbFGhw8azBSk6n5mBAiE=
