os: linux
dist: jammy
group: dev
language: ruby

# Specify Ruby version
rvm:
  - 2.7.8

script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo $TRAVIS_EVENT_TYPE
  - ruby -v  # Print the Ruby version to confirm it is 2.7.8

deploy:
  provider: pages
  cleanup: false  # Use cleanup instead of skip_cleanup
  token: $GITHUB_TOKEN  
  keep_history: true
  on:
    branch: main
  dpl_version: 1.x  # Ensure dpl 1.x is used as the default



