os: linux
dist: jammy
group: dev
language: shell
script:
- echo $TRAVIS_BRANCH
- echo $TRAVIS_TAG
- echo $TRAVIS_EVENT_TYPE
deploy:
  provider: lambda
  function_name: lambda-test
  region: us-east-1
  role: arn:aws:iam::341288657826:role/lambda_basic_execution
  runtime: nodejs18.x
  handler_name: main
  edge:
    branch: tbt_4_am
  on:
    branch: main
  
