dist: focal
language: ruby
rvm:
  - 3.1
  - 3.2
  - 3.3

cache:
  - bundler
@@ -18,14 +19,16 @@ jobs:
      if: commit_message !~ /skip:test_dependencies/ AND env(SKIP_TEST_DEPENDENCIES) IS blank
      cache: false
      install:
      - rvm use 3.3 --install --binary --fuzzy
      - gem build dpl.gemspec
      - gem install dpl-*.gem
      - nvm install 12.22.0
      - nvm use 12.22.0
      - gem update --system
      - nvm install 18.20.2
      - nvm use 18.20.2
      - node --version
      script:
      - .travis/test_install
      rvm: 3.1
      rvm: 3.3
    - <<: *job
      language: python
      python: 2.7



