os: linux

vm:
  size: [large]
language: java
services:
  - docker
cache: bundler
dist: bionic

jobs:
  include:
    - os: linux
      dist: focal
      addons:
        sbom:                                          
          on:
            branch: 'main'                 
          run_phase: 'after_success'                  
          output_format: 'cyclonedx-json'              # SBOM file(s) output format
          input_dir: '/sbom/ruby'                      # relative paths within build job environments, see below
          output_dir: '/sbom/ruby'
  

 







  


