
os: linux
vm:
  size: [large]
language: java
services:
  - docker
cache: bundler
dist: bionic
 addons:
     snaps:
       - name: aws-cli
         confinement: classic # or devmode
         channel: latest/edge # will be passed to --channel flag

install: skip

jobs:
  include:
    - name: failing
      script: true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULTos: linux
