os: linux
dist: focal
language: ruby
jobs:
include:

name: “test” # existing functionality
script: # existing functionality

ruby --version
name: “sbom”
script: # existing functionality

cd ruby
bundle install
addons:
sbom:
on:
branch: 'main'
pr: true

condition: false
run_phase: "after_success" #
output_format: "spdx-json" #
output_dir: "/test" #
input_dir: "/ruby" #
User has created a single container with  SBOM Tooling  installed







